ocular:
  # path: examples/adder_n28.qasm
  # path: examples/adder_n64.qasm
  # path: examples/adder_n10_medium.qasm
  # path: examples/adder_n10_shortened.qasm
  # path: examples/adder_n4.qasm
  # path: /home/jakob/Documents/hamiltonians/ham_heis_graph_2D_grid_nonpbc_qubitnodes_Lx_5_Ly_186_h_0_5.qasm
  path: /home/jakob/Documents/hamiltonians/ham_heis_graph_2D_grid_pbc_qubitnodes_Lx_5_Ly_186_h_3.qasm
  # path: /home/jakob/Documents/hamiltonians/ham_BH_D_1_d_4_bh_graph_1D_grid_nonpbc_qubitnodes_Lx_12_U_40_enc_unary_d_4.qasm
  trials: 1
  layer: 1
  heuristics:
    - "lookahead"
